name: neosurge
description: Mobile application for bullsurge.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.49+149

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  gap: ^3.0.1
  flutter_svg: ^2.0.7
  flutter_signin_button: ^2.0.0
  dotted_line: ^3.2.2
  signature: ^5.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  lottie: ^2.5.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.63.0
  pinput: ^2.2.31
  dio: ^5.3.2
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  another_xlider: ^3.0.1
  shimmer: ^3.0.0
  google_sign_in: ^6.1.4
  camera: ^0.10.5+5
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  local_auth: ^2.1.6
  fluttertoast: ^8.2.2
  currency_text_input_formatter: ^2.1.10
  dotted_border: ^2.0.0+3
  http_parser: ^4.0.2
  image_picker: ^1.0.2
  dropdown_search: ^5.0.6
  video_player: ^2.7.0
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.9.2
  webview_flutter_wkwebview: ^3.7.2
  sliver_tools: ^0.2.12
  flutter_keyboard_visibility: ^5.4.1
  path_provider: ^2.1.0
  video_compress: ^3.1.2
  cached_network_image: ^3.2.3
  razorpay_flutter: ^1.3.5
  enhance_stepper: ^0.1.1
  # provider: ^6.0.5
  injectable: ^2.2.0
  flutter_hooks: ^0.19.0
  flutter_downloader: ^1.6.5
  permission_handler: ^10.4.3
  jiffy: ^6.2.1
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.2
  expandable_sliver_list: ^4.1.1
  geolocator: ^9.0.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  location: ^5.0.1
  firebase_crashlytics: ^3.3.4
  scrollable_positioned_list: ^0.3.8
  device_info_plus: ^9.0.3
  awesome_snackbar_content: ^0.1.3
  sign_in_with_apple: ^5.0.0
  app_version_update: ^4.0.1
  percent_indicator: ^4.2.3
  syncfusion_flutter_gauges: ^24.2.8
  google_mlkit_text_recognition: ^0.10.0
  image_cropper: ^5.0.0
  scgateway_flutter_plugin: ^2.3.1
  font_awesome_flutter: ^9.2.0
  loading_animation_widget: ^1.2.0+4
  carousel_slider: ^4.2.1
  share_plus: ^7.2.1
  sentry_flutter: ^7.16.0
  flutter_staggered_grid_view: ^0.7.0
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_sliders: ^24.2.8
  amplitude_flutter: ^3.16.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  injectable_generator: ^2.2.0
  flutter_flavorizr: ^2.2.1
  dependency_validator: ^3.2.2
  # dart_code_metrics: ^5.7.5

dependency_overrides:
  #  flutter_svg: ^2.0.2
  intl: ^0.18.1
  collection: ^1.18.0
  # http: ^1.1.0

flutter_icons:
  image_path: "assets/app_icons/app_icon.png"
  adaptive_icon_foreground: "assets/app_icons/app_icon_foreground.png"
  adaptive_icon_background: "#ffffff"
  android: true
  remove_alpha_ios: true
  ios: true

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/svgs/
    - assets/pngs/
    - assets/icons/
    - assets/icons/bottom_nav_bar/
    - assets/animations/
    - assets/gifs/
    - assets/app_icons/
flavorizr:
  flavors:
    dev:
      app:
        name: "Neosurge Dev"

      android:
        applicationId: "com.neosurge.neosurge"

      ios:
        bundleId: "com.neosurge.neosurge"

    staging:
      app:
        name: "Neosurge Staging"

      android:
        applicationId: "com.neosurge.neosurge"

      ios:
        bundleId: "com.neosurge.neosurge"

    prod:
      app:
        name: "Neosurge"

      android:
        applicationId: "com.neosurge.neosurge"
      ios:
        bundleId: "com.neosurge.neosurge"
