class FilterSortValues {
  const FilterSortValues._();

  static List<String> filters = [
    "AMC",
    "Asset Categories",
    "Asset Sub Categories",
    "Ratings",
    "Risks"
  ];

  static const List<String> assetCategories = [
    "Commodity",
    "Equity",
    "Fixed Income",
    "Global",
    "Hybrid",
  ];

  static const List<String> assetSubCategories = [
    "10 Y Gilt",
    "Aggressive Hybrid Fund",
    "Arbitrage",
    "Banking & PSU Fund",
    "Conservative Hybrid Fund",
    "Corporate Bond Fund",
    "Country Specific - Brazil",
    "Country Specific - China",
    "Country Specific - Japan",
    "Country Specific - Taiwan",
    "Country Specific - US",
    "Credit Risk Fund",
    "Debt - FOF",
    "Diversified",
    "Dynamic Asset Allocation",
    "Dynamic Bond",
    "Equity - FOF",
    "Equity Savings Fund",
    "ETF",
    "Flexi - Cap",
    "Floater Fund",
    "Focused",
    "Fund of Fund",
    "Fund of Funds - Gold",
    "Gilt Fund",
    "Global - FOF",
    "Hybrid - Domestic & Global Equity",
    "Index",
    "Large & Mid Cap",
    "Large Cap",
    "Liquid",
    "Long Duration Fund",
    "Low Duration Fund",
    "Medium Duration Fund",
    "Medium to Long Duration Fund",
    "Mid Cap",
    "Money Market Fund",
    "Multi - Cap",
    "Multi Asset Allocation",
    "Overnight Fund",
    "Region Specific - ASEAN",
    "Region Specific - ASIA",
    "Region Specific - Emerging Markets",
    "Region Specific - Europe",
    "Sector Specific - Banks & Financial",
    "Sector Specific - Diversified",
    "Sector Specific - FMCG",
    "Sector Specific - Pharma",
    "Sector Specific - Technology",
    "Sector Specific - Transportation",
    "Short Duration Fund",
    "Small Cap",
    "Solution Oriented - Children's Fund",
    "Solution Oriented - Retirement",
    "Tax Savings",
    "Thematic - Agriculture & Food",
    "Thematic - Business Cycles",
    "Thematic - Commodities",
    "Thematic - Consumption",
    "Thematic - Contra",
    "Thematic - Dividend Yield",
    "Thematic - Energy",
    "Thematic - ESG",
    "Thematic - Infrastructure",
    "Thematic - Innovation",
    "Thematic - IPO",
    "Thematic - Manfacturing",
    "Thematic - Mining & Metals",
    "Thematic - MNC",
    "Thematic - Precious Metals",
    "Thematic - PSU",
    "Thematic - Quant",
    "Thematic - Real Estate",
    "Thematic - Rural & Agriculture",
    "Thematic - Service Industries",
    "Thematic - Shariah",
    "Ultra Short Duration Fund",
    "Value Fund",
  ];

  static List<String> amcNameList = [
    "Aditya Birla Sun Life AMC Limited",
    "Axis Asset Management Company Ltd.",
    "BOI AXA Investment Managers Private Limited",
    "Canara Robeco Asset Management Company Limited",
    "PGIM India Asset Management Private Limited",
    "DSP Investment Managers Private Limited",
    "Edelweiss Asset Management Limited",
    "Navi AMC Limited",
    "Franklin Templeton Asset Management (India) Private Limited",
    "HDFC Asset Management Company Limited",
    "HSBC Global Asset Management (India) Private Limited",
    "ICICI Prudential Asset Management Company Limited",
    "IDBI Asset Management Ltd.",
    "IDFC Asset Management Company Limited",
    "IIFL Asset Management Co. Ltd.",
    "Indiabulls Asset Management Company Limited",
    "Invesco Asset Management Company Pvt Ltd.",
    "JM Financial Asset Management Private Limited",
    "Kotak Mahindra Asset Management Company Limited",
    "L&T Investment Management Limited",
    "LIC Mutual Fund Asset Management Limited",
    "Mahindra Manulife Investment Management Private Limited",
    "Mirae Asset Investment Managers (India) Private Limited",
    "Motilal Oswal Asset Management Company Limited",
    "PPFAS Asset Management Pvt. Ltd.",
    "Quant Money Managers Limited",
    "Quantum Asset Management Company Private Limited",
    "Nippon Life India Asset Management Limited",
    "SBI Funds Management Limited",
    "Shriram Asset Management Company Limited",
    "Sundaram Asset Management Company Limited",
    "Tata Asset Management Private Limited",
    "Taurus Asset Management Company Limited",
    "Union Asset Management Company Pvt. Ltd.",
    "UTI Asset Management Company Private Limited",
    "WhiteOak Capital Asset Management Limited",
    "ITI Asset Management Limited",
    "Trust Asset Management Private Limited",
    "Samco Asset Management Pvt. Ltd.",
    "NJ Asset Management Private Limited",
    "Baroda BNP Paribas Asset Management India Pvt. Ltd."
  ];

  static const List<AmcValue> amcList = [
    AmcValue("AMC1", "Aditya Birla Sun Life AMC Limited"),
    AmcValue("AMC2", "Axis Asset Management Company Ltd."),
    AmcValue("AMC5", "BOI AXA Investment Managers Private Limited"),
    AmcValue("AMC6", "Canara Robeco Asset Management Company Limited"),
    AmcValue("AMC7", "PGIM India Asset Management Private Limited"),
    AmcValue("AMC8", "DSP Investment Managers Private Limited"),
    AmcValue("AMC9", "Edelweiss Asset Management Limited"),
    AmcValue("AMC10", "Navi AMC Limited"),
    AmcValue(
        "AMC11", "Franklin Templeton Asset Management (India) Private Limited"),
    AmcValue("AMC12", "HDFC Asset Management Company Limited"),
    AmcValue("AMC13", "HSBC Global Asset Management (India) Private Limited"),
    AmcValue("AMC14", "ICICI Prudential Asset Management Company Limited"),
    AmcValue("AMC15", "IDBI Asset Management Ltd."),
    AmcValue("AMC16", "IDFC Asset Management Company Limited"),
    AmcValue("AMC17", "IIFL Asset Management Co. Ltd."),
    AmcValue("AMC18", "Indiabulls Asset Management Company Limited"),
    AmcValue("AMC19", "Invesco Asset Management Company Pvt. Ltd."),
    AmcValue("AMC20", "JM Financial Asset Management Private Limited"),
    AmcValue("AMC21", "Kotak Mahindra Asset Management Company Limited"),
    AmcValue("AMC22", "L&T Investment Management Limited"),
    AmcValue("AMC23", "LIC Mutual Fund Asset Management Limited"),
    AmcValue(
        "AMC24", "Mahindra Manulife Investment Management Private Limited"),
    AmcValue(
        "AMC25", "Mirae Asset Investment Managers (India) Private Limited"),
    AmcValue("AMC26", "Motilal Oswal Asset Management Company Limited"),
    AmcValue("AMC27", "PPFAS Asset Management Pvt. Ltd."),
    AmcValue("AMC29", "Quant Money Managers Limited"),
    AmcValue("AMC30", "Quantum Asset Management Company Private Limited"),
    AmcValue("AMC31", "Nippon Life India Asset Management Limited"),
    AmcValue("AMC33", "SBI Funds Management Limited"),
    AmcValue("AMC34", "Shriram Asset Management Company Limited"),
    AmcValue("AMC35", "Sundaram Asset Management Company Limited"),
    AmcValue("AMC36", "Tata Asset Management Private Limited"),
    AmcValue("AMC37", "Taurus Asset Management Company Limited"),
    AmcValue("AMC38", "Union Asset Management Company Pvt. Ltd."),
    AmcValue("AMC39", "UTI Asset Management Company Private Limited"),
    AmcValue("AMC40", "WhiteOak Capital Asset Management Limited"),
    AmcValue("AMC41", "ITI Asset Management Limited"),
    AmcValue("AMC42", "Trust Asset Management Private Limited"),
    AmcValue("AMC43", "Samco Asset Management Pvt. Ltd."),
    AmcValue("AMC44", "NJ Asset Management Private Limited"),
    AmcValue("AMC45", "Baroda BNP Paribas Asset Management India Pvt. Ltd."),
  ];

  static List<String> riskList = [
    //Aggressive
    // Moderately Aggressive
    // Conservative
    // Moderately Conservative
    // Balanced

    "Aggressive",
    "Moderately Aggressive",
    "Conservative",
    "Moderately Conservative",
    "Balanced"
  ];
}

class AmcValue {
  final String amcCode;
  final String amcName;

  const AmcValue(this.amcCode, this.amcName);
}
