// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIwV153QEKiXUpR_EDT3fmFsnf9wnkOTo',
    appId: '1:901855431398:android:0d2e4c7b010e580e03c927',
    messagingSenderId: '901855431398',
    projectId: 'neosurge-2cb42',
    storageBucket: 'neosurge-2cb42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf_DL83PUOfgELxkZ9bGPQuh1j-cSm3Ts',
    appId: '1:901855431398:ios:1f58bb9b470efba503c927',
    messagingSenderId: '901855431398',
    projectId: 'neosurge-2cb42',
    storageBucket: 'neosurge-2cb42.appspot.com',
    androidClientId:
        '901855431398-0533d84gtch6b9at4fk2bmts0771hfv5.apps.googleusercontent.com',
    iosClientId:
        '901855431398-83uq6r2mbjun1pc8uv4loikpk5buat6g.apps.googleusercontent.com',
    iosBundleId: 'com.neosurge.neosurge',
  );
}
